import { PRODUCT_NAME } from "@/lib/branding/product-name";
import {
  LEGAL_PLACEHOLDERS,
  PRIVACY_DRAFT_BANNER,
  legalDocumentMeta,
  type LegalSection,
} from "@/lib/legal/document";
import { legalOperatorIdentity } from "@/lib/legal/status";

const P = LEGAL_PLACEHOLDERS;
const OPERATOR = legalOperatorIdentity(PRODUCT_NAME);

const SECTIONS: readonly LegalSection[] = [
  {
    id: "who",
    title: "1. Who River Aftercare is",
    blocks: [
      {
        type: "placeholder",
        text: `${PRODUCT_NAME} is operated by ${OPERATOR}.`,
      },
      {
        type: "p",
        text: `${PRODUCT_NAME} is an Australian B2B publishing platform for healthcare practices. It helps clinics publish clinic-branded treatment, recovery, home-care and aftercare guidance on the web. The platform is designed for treatment-based practices including dental, cosmetic and aesthetic clinics, physiotherapy, chiropractic and allied health.`,
      },
    ],
  },
  {
    id: "scope",
    title: "2. Scope",
    blocks: [
      {
        type: "p",
        text: "This Privacy Policy explains how we handle personal information in connection with:",
      },
      {
        type: "ul",
        items: [
          `the public ${PRODUCT_NAME} marketing website;`,
          "clinic enquiries submitted through the Contact form;",
          "clinic and staff accounts;",
          "practice configuration, branding and published aftercare content; and",
          "readers of public clinic-branded aftercare pages.",
        ],
      },
      {
        type: "p",
        text: "This policy is written to a high Australian privacy standard. It does not state whether River Aftercare is an APP entity under the Privacy Act 1988 (Cth). That status has not been determined in this document.",
      },
    ],
  },
  {
    id: "personal-information",
    title: "3. Personal information we collect",
    blocks: [
      {
        type: "p",
        text: "Depending on how you interact with us, we may collect:",
      },
      {
        type: "ul",
        items: [
          "marketing enquiry details: name, work email, clinic or practice name, optional phone number, and any message you choose to send;",
          "clinic staff account details: name (if provided), email address, password stored as a one-way hash, clinic membership and role, and session data needed to stay signed in;",
          "practice configuration such as display name, contact details, emergency instructions, colours, presentation settings, logos (where logo upload is enabled), and aftercare guides or other clinic-published content; and",
          "technical information generated by hosting or application systems, which may include IP address, user agent, requested URL, HTTP status and timestamp.",
        ],
      },
      {
        type: "p",
        text: "We collect only what is reasonably needed for the relevant interaction. We do not collect a category of information merely because the underlying software could do so.",
      },
    ],
  },
  {
    id: "not-designed-to-collect",
    title: "4. Information the current product is not designed to collect",
    blocks: [
      {
        type: "p",
        text: `${PRODUCT_NAME} is not currently designed for users to enter identifiable patient health records or personalised patient information.`,
      },
      {
        type: "p",
        text: "Clinics and other users must not submit through the current product:",
      },
      {
        type: "ul",
        items: [
          "patient names attached to clinical data;",
          "dates of birth;",
          "Medicare numbers;",
          "medical record numbers;",
          "diagnoses;",
          "clinical histories;",
          "treatment records; or",
          "other identifiable patient health information,",
        ],
      },
      {
        type: "p",
        text: `unless ${PRODUCT_NAME} later introduces functionality explicitly designed for that purpose and updates its privacy, security and contractual arrangements.`,
      },
      {
        type: "p",
        text: "Some forms include free-text fields (for example an enquiry message or clinic-authored guide copy). Those fields are intended for business contact details and generic aftercare instructions, not for patient records. Please do not enter identifiable patient information into them.",
      },
    ],
  },
  {
    id: "how-collected",
    title: "5. How information is collected",
    blocks: [
      {
        type: "p",
        text: "We collect information:",
      },
      {
        type: "ul",
        items: [
          "directly from you when you submit the Contact form, create or use a staff account, or configure a clinic;",
          "from authorised clinic users who enter practice details, branding and aftercare content; and",
          "automatically, to the extent hosting or application systems generate technical logs when the service is used.",
        ],
      },
      {
        type: "p",
        text: "The Contact form includes a hidden field used only to reduce automated spam. That field is not intended to collect personal information from people filling in the form.",
      },
    ],
  },
  {
    id: "how-used",
    title: "6. How we use information",
    blocks: [
      {
        type: "p",
        text: "We use personal information to:",
      },
      {
        type: "ul",
        items: [
          "respond to clinic enquiries and operate an assisted onboarding or commercial relationship;",
          "create and administer clinic and staff accounts;",
          "host, display and maintain clinic-branded aftercare pages;",
          "provide support, security, troubleshooting and service communications;",
          "meet legal, accounting and dispute-related obligations; and",
          "improve the reliability and operation of the service.",
        ],
      },
      {
        type: "p",
        text: "We do not sell personal information.",
      },
    ],
  },
  {
    id: "public-guides",
    title: "7. Public aftercare guides",
    blocks: [
      {
        type: "p",
        text: "Public aftercare pages are published by the clinic on a clinic hostname. They present clinic-branded procedure guidance. The URL identifies a clinic and a procedure or guide (for example a tooth-extraction page). It does not identify a named patient.",
      },
      {
        type: "p",
        text: "Generic public guides do not require a patient account and are not designed to collect reader personal information. Anyone with the link can open the page, in the same way they can open a public practice webpage.",
      },
    ],
  },
  {
    id: "staff-accounts",
    title: "8. Clinic and staff account information",
    blocks: [
      {
        type: "p",
        text: "Staff accounts are for clinic personnel and, where relevant, platform operators. We store the account name (if provided), email address, a hashed password, clinic membership and role, and session records needed to authenticate the user.",
      },
      {
        type: "p",
        text: "Platform operators who administer clinics can see clinic identity and configuration. They do not receive a patient health record through the current product, because the current product is not designed to hold one.",
      },
    ],
  },
  {
    id: "practice-configuration",
    title: "9. Practice configuration and branding",
    blocks: [
      {
        type: "p",
        text: "A clinic may store operational and branding information used to present its aftercare pages, including practice display name, colours, radius and theme settings, instruction terminology, clinic contact details, emergency instructions, logos where upload is enabled, and the aftercare guides the clinic creates or adapts.",
      },
      {
        type: "p",
        text: "That information is clinic operational data. It is shown on the clinic’s patient pages under the clinic’s brand.",
      },
    ],
  },
  {
    id: "technical",
    title: "10. Technical and log information",
    blocks: [
      {
        type: "p",
        text: "The systems that host the service may record technical information commonly generated by web applications, such as IP address, user agent, requested URL, HTTP status and timestamp. This information is used to operate, secure and diagnose the service.",
      },
    ],
  },
  {
    id: "cookies",
    title: "11. Cookies and local browser storage",
    blocks: [
      {
        type: "p",
        text: "Staff authentication uses a host-only session cookie on the staff hostname. The cookie is HttpOnly, uses SameSite=Lax, and is marked Secure in production. It is used to keep an authorised user signed in. It is not an advertising tracker.",
      },
      {
        type: "p",
        text: "Appearance preferences (Light, Dark or System) may be stored in the browser’s localStorage on the marketing site, the staff portal, and public aftercare pages where a clinic enables a patient theme control. These preferences stay on the device and are not advertising cookies.",
      },
      {
        type: "p",
        text: "We do not currently operate a cookie-consent marketing stack, because we do not currently run marketing analytics or advertising pixels.",
      },
    ],
  },
  {
    id: "analytics",
    title: "12. Analytics",
    blocks: [
      {
        type: "p",
        text: `${PRODUCT_NAME} does not currently use third-party behavioural advertising or advertising pixels on its public website or public aftercare guides.`,
      },
      {
        type: "p",
        text: "We do not currently operate a marketing analytics product on those pages. If that changes, we will update this policy before any such processing begins.",
      },
    ],
  },
  {
    id: "disclosure",
    title: "13. Disclosure to service providers",
    blocks: [
      {
        type: "p",
        text: "We may disclose personal information to service providers who help us operate the service, strictly as needed for that purpose. Those providers may fall into categories such as:",
      },
      {
        type: "ul",
        items: [
          "application hosting;",
          "database hosting;",
          "object or file storage for clinic logos and similar assets;",
          "DNS and network services;",
          "email delivery; and",
          "monitoring or security services.",
        ],
      },
      {
        type: "p",
        text: "We will name production service providers in this policy once those arrangements are finalised. Contact enquiries are delivered by email using the mail transport configured for the application. They are not stored as enquiry records in the application database.",
      },
    ],
  },
  {
    id: "overseas",
    title: "14. Overseas processing",
    blocks: [
      {
        type: "p",
        text: `${PRODUCT_NAME} is operated from Australia and is aimed at Australian healthcare practices. Some service providers may process information outside Australia. We will update this Policy as our production service-provider arrangements are finalised.`,
      },
    ],
  },
  {
    id: "security",
    title: "15. Security",
    blocks: [
      {
        type: "p",
        text: "We take reasonable technical and organisational measures designed to protect personal information from misuse, interference, loss and unauthorised access, modification or disclosure.",
      },
      {
        type: "p",
        text: "Those measures currently include:",
      },
      {
        type: "ul",
        items: [
          "storing staff passwords as one-way hashes rather than in usable form;",
          "access control based on authenticated sessions, clinic membership and role;",
          "clinic authorisation boundaries so staff act within their own clinic;",
          "host-only, HttpOnly session cookies with SameSite=Lax, marked Secure in production;",
          "separated hostnames for the public marketing site, staff portal and clinic patient pages; and",
          "HTTPS for production access once the service is deployed on a public hostname.",
        ],
      },
      {
        type: "p",
        text: "No method of transmission or storage is completely secure. We do not claim ISO, SOC, HIPAA or Privacy Act certification, encryption-at-rest guarantees, or a completed independent penetration-test status.",
      },
    ],
  },
  {
    id: "data-breach",
    title: "16. Data breach response",
    blocks: [
      {
        type: "p",
        text: `If we become aware of a suspected security incident affecting personal information, ${PRODUCT_NAME} will investigate, take reasonable containment and remediation steps, and make any notifications required by applicable law, including under the Notifiable Data Breaches scheme where that scheme applies to ${PRODUCT_NAME} in the relevant circumstances.`,
      },
    ],
  },
  {
    id: "retention",
    title: "17. Retention and deletion",
    blocks: [
      {
        type: "p",
        text: "We keep personal information only for as long as reasonably needed for the purposes described in this policy, or as required by law. Our intended retention approach is:",
      },
      {
        type: "ul",
        items: [
          "Contact and enquiry personal information: normally up to 12 months after the last meaningful interaction, unless needed longer for an active commercial relationship, a legal obligation or a dispute.",
          `Active clinic and staff account information: while the clinic has an active relationship with ${PRODUCT_NAME}.`,
          "Terminated clinic operational data: we aim to delete active clinic account and operational data after a 30-day exit period following the end of the subscription, unless it is still required.",
          "Security and application logs: we aim to retain them for about 90 days, unless a security incident, legal obligation or infrastructure requirement reasonably requires longer.",
          "Backups: where production architecture permits, we aim to rotate or overwrite backups so that deleted operational data is not retained in backups for longer than about 90 days after active deletion.",
          "Billing, accounting and tax records: retained for the period required by Australian law, which is commonly at least 5 years and may be longer in a particular circumstance.",
        ],
      },
      {
        type: "p",
        text: "These periods describe our intended operating practice. Exact backup and deletion timing depends on the production hosting and backup arrangements in place at the time.",
      },
    ],
  },
  {
    id: "communications",
    title: "18. Direct marketing and service communications",
    blocks: [
      {
        type: "p",
        text: "We distinguish operational messages from marketing messages.",
      },
      {
        type: "ul",
        items: [
          "Operational or service messages include responses to an enquiry, account, billing, security and similar messages needed to provide or administer the service.",
          "Marketing or promotional messages are electronic messages sent to promote River Aftercare rather than to operate an existing account or complete a requested enquiry.",
        ],
      },
      {
        type: "p",
        text: "Commercial electronic marketing will comply with applicable Australian law and will include an unsubscribe mechanism where required.",
      },
    ],
  },
  {
    id: "access",
    title: "19. Access and correction",
    blocks: [
      {
        type: "p",
        text: "You may request access to, or correction of, personal information we hold about you, where applicable. We may need to verify your identity before responding. Clinic administrators can also update much of their practice configuration in the staff portal.",
      },
      {
        type: "p",
        text: "Please do not include patient records in an access or correction request sent through the Contact form.",
      },
    ],
  },
  {
    id: "complaints",
    title: "20. Privacy complaints",
    blocks: [
      {
        type: "p",
        text: `If you have a privacy complaint, contact us using the details in section 24, or through the Contact page on this website. We may ask for enough information to verify the request and investigate the complaint. We will acknowledge and investigate complaints and aim to respond within 30 days.`,
      },
      {
        type: "p",
        text: "If you are not satisfied with our response, the Office of the Australian Information Commissioner (OAIC) may be available to assist where applicable.",
      },
    ],
  },
  {
    id: "children",
    title: "21. Children",
    blocks: [
      {
        type: "p",
        text: `${PRODUCT_NAME} is a business platform and does not provide child accounts. Public aftercare guides can be viewed by anyone with the link, including children or parents and guardians. Generic guides are not designed to collect reader personal information.`,
      },
    ],
  },
  {
    id: "automated-decisions",
    title: "22. Automated decision-making",
    blocks: [
      {
        type: "p",
        text: `${PRODUCT_NAME} does not currently use personal information to make automated decisions that could reasonably be expected to significantly affect an individual's rights or interests.`,
      },
    ],
  },
  {
    id: "changes",
    title: "23. Changes to this policy",
    blocks: [
      {
        type: "p",
        text: "We may update this Privacy Policy from time to time, including when our product, service-provider arrangements or legal obligations change. The “Last updated” date on this page will change when we do. Material changes will be published on this page.",
      },
    ],
  },
  {
    id: "contact",
    title: "24. Contact",
    blocks: [
      {
        type: "p",
        text: `For privacy questions or requests, use the Contact page on this website or write to the privacy contact below. Please do not include patient or clinical records in that correspondence.`,
      },
      {
        type: "placeholder",
        text: `${OPERATOR}. Privacy contact: ${P.privacyEmail}.`,
      },
    ],
  },
];

export const PRIVACY_DOCUMENT = legalDocumentMeta({
  slug: "/privacy",
  title: "Privacy Policy",
  intro: `This Privacy Policy describes how ${PRODUCT_NAME} handles information on the public marketing website, in clinic and staff accounts, and on clinic-branded public aftercare pages. The current product is a clinic publishing platform. It is not a patient health record.`,
  draftBanner: PRIVACY_DRAFT_BANNER,
  sections: SECTIONS,
});
