#!/usr/bin/env bash
# Per-boot Cloud Agent startup. Safe to run again.
# Starts local PostgreSQL 18, applies committed migrations, then seeds.
set -euo pipefail

cd "$(dirname "$0")/.."

export DEBIAN_FRONTEND=noninteractive
export COREPACK_ENABLE_DOWNLOAD_PROMPT=0

if [[ "${VERCEL_ENV:-}" == "production" ]]; then
  echo "Refusing Cloud startup: VERCEL_ENV=production is not part of Cloud development." >&2
  exit 1
fi

if [[ -n "${RIVER_AFTERCARE_PRODUCTION_MIGRATE:-}" ]]; then
  echo "Refusing Cloud startup: RIVER_AFTERCARE_PRODUCTION_MIGRATE must not be set." >&2
  exit 1
fi

if [[ -n "${SKIP_PRODUCTION_SCHEMA_GATE:-}" ]]; then
  echo "Refusing Cloud startup: SKIP_PRODUCTION_SCHEMA_GATE must not be set." >&2
  exit 1
fi

if [[ -n "${DIRECT_URL:-}" ]]; then
  echo "Refusing Cloud startup: DIRECT_URL must not be set. Cloud development uses local DATABASE_URL only." >&2
  exit 1
fi

refuse_if_set() {
  local name="$1"
  if [[ -n "${!name:-}" ]]; then
    echo "Refusing Cloud startup: ${name} must not be set. Cloud development does not use that production service." >&2
    exit 1
  fi
}

refuse_if_set RESEND_API_KEY
refuse_if_set R2_ACCOUNT_ID
refuse_if_set R2_ACCESS_KEY_ID
refuse_if_set R2_SECRET_ACCESS_KEY
refuse_if_set STRIPE_SECRET_KEY
refuse_if_set STRIPE_WEBHOOK_SECRET
refuse_if_set SENTRY_AUTH_TOKEN
refuse_if_set SENTRY_DSN
refuse_if_set NEXT_PUBLIC_SENTRY_DSN

node --input-type=module <<'EOF'
const databaseUrl = process.env.DATABASE_URL ?? "";
const e2eUrl = process.env.E2E_DATABASE_URL ?? "";

function rejectNeon(raw) {
  if (/neon\.tech/i.test(raw)) {
    console.error("Refusing Cloud startup: a Neon database URL is set.");
    process.exit(1);
  }
}

function inspect(raw, label, expectedDatabase, allowEmpty) {
  if (!raw) {
    if (allowEmpty) {
      return;
    }
    console.error(`Refusing Cloud startup: ${label} is missing.`);
    process.exit(1);
  }
  rejectNeon(raw);
  let url;
  try {
    url = new URL(raw);
  } catch {
    console.error(`Refusing Cloud startup: ${label} could not be parsed.`);
    process.exit(1);
  }
  const database = decodeURIComponent(url.pathname.replace(/^\//, "")).split("/")[0];
  const hostname = url.hostname;
  const port = url.port || "5432";
  const username = decodeURIComponent(url.username);
  const password = decodeURIComponent(url.password);
  const localHost = hostname === "localhost" || hostname === "127.0.0.1";
  if (
    !localHost ||
    port !== "5432" ||
    database !== expectedDatabase ||
    username !== "postgres" ||
    password !== "postgres"
  ) {
    console.error(
      `Refusing Cloud startup: ${label} must target local PostgreSQL database ${expectedDatabase}.`
    );
    process.exit(1);
  }
}

inspect(databaseUrl, "DATABASE_URL", "care_guide", true);
inspect(e2eUrl, "E2E_DATABASE_URL", "care_guide_e2e", true);
EOF

cat > .env <<'EOF'
# Generated by scripts/cursor-cloud-start.sh for the isolated Cloud VM.
# Non-secret local defaults only. Do not add production credentials.
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/care_guide?schema=public"
E2E_DATABASE_URL="postgresql://postgres:postgres@localhost:5432/care_guide_e2e?schema=public"
CARE_GUIDE_ROOT_DOMAIN="localhost"
CONTACT_EMAIL_TO="hello@example.test"
CONTACT_EMAIL_FROM="River Aftercare <website@example.test>"
CONTACT_MAILER="memory"
NEXT_PUBLIC_TURNSTILE_SITE_KEY="1x00000000000000000000AA"
TURNSTILE_SECRET_KEY="1x0000000000000000000000000000000AA"
AUTH_EMAIL_FROM="River Aftercare <accounts@example.test>"
AUTH_EMAIL_REPLY_TO="hello@example.test"
CLINIC_ASSET_STORAGE_DRIVER="filesystem"
CLINIC_ASSET_FILESYSTEM_ROOT=".data/clinic-assets"
EOF

export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/care_guide?schema=public"
export E2E_DATABASE_URL="postgresql://postgres:postgres@localhost:5432/care_guide_e2e?schema=public"
export CARE_GUIDE_ROOT_DOMAIN="${CARE_GUIDE_ROOT_DOMAIN:-localhost}"
export CONTACT_MAILER="${CONTACT_MAILER:-memory}"
export CLINIC_ASSET_STORAGE_DRIVER="${CLINIC_ASSET_STORAGE_DRIVER:-filesystem}"

# The Cloud base image does not implement RFC 6761 *.localhost.
# dnsmasq answers every name under .localhost on 127.0.0.1 so tenant
# Host routing keeps working. Machines that already resolve it are unchanged.
if ! getent hosts app.localhost >/dev/null 2>&1; then
  if ! command -v dnsmasq >/dev/null 2>&1; then
    echo "app.localhost does not resolve, and dnsmasq is not installed." >&2
    exit 1
  fi
  upstream="/run/cursor-cloud-upstream-resolv.conf"
  if [[ ! -s "${upstream}" ]]; then
    awk '/^nameserver / && $2 != "127.0.0.1" { print }' /etc/resolv.conf | sudo tee "${upstream}" >/dev/null
  fi
  if [[ ! -s "${upstream}" ]]; then
    echo "Could not discover an upstream nameserver for Cloud DNS." >&2
    exit 1
  fi
  sudo tee /etc/dnsmasq.d/cursor-cloud-localhost.conf >/dev/null <<'EOF'
address=/localhost/127.0.0.1
listen-address=127.0.0.1
bind-interfaces
no-hosts
EOF
  if ! pgrep -x dnsmasq >/dev/null 2>&1; then
    sudo dnsmasq \
      --conf-file=/etc/dnsmasq.d/cursor-cloud-localhost.conf \
      --resolv-file="${upstream}"
  fi
  printf 'nameserver 127.0.0.1\n' | sudo tee /etc/resolv.conf >/dev/null
  if ! getent hosts app.localhost >/dev/null 2>&1; then
    echo "RFC 6761 *.localhost resolution is still unavailable." >&2
    exit 1
  fi
fi

if ! docker info >/dev/null 2>&1; then
  sudo service docker start
  ready=0
  for _ in $(seq 1 30); do
    if docker info >/dev/null 2>&1; then
      ready=1
      break
    fi
    sleep 1
  done
  if [[ "${ready}" != "1" ]]; then
    echo "Docker did not become usable during Cloud startup." >&2
    exit 1
  fi
fi

docker compose up -d

ready=0
for _ in $(seq 1 60); do
  if docker compose exec -T postgres pg_isready -U postgres -d care_guide >/dev/null 2>&1; then
    ready=1
    break
  fi
  sleep 1
done

if [[ "${ready}" != "1" ]]; then
  echo "PostgreSQL 18 did not become ready on care_guide." >&2
  docker compose ps || true
  docker compose logs --tail 80 postgres || true
  exit 1
fi

pnpm exec prisma migrate deploy --config prisma.config.ts
pnpm db:seed

echo "Cloud startup finished: local care_guide is migrated and seeded."
